#CHECK THE USERS FUNCTIONS
# GET http://localhost:3000/users
# Content-Type: application/json

# GET http://localhost:3000/users/1
# Content-Type: application/json

# POST http://localhost:3000/users
# Content-Type: application/json

# {
#   "name": "Rut Doe",
#   "username": "r",
#   "email": "johndoe@example.com",
#   "address": "mypassword",
#   "phone": "058"
# }


#  DELETE http://localhost:3000/users/11
#  DELETE http://localhost:3000/users/14


# PUT http://localhost:3000/users/1
# Content-Type: application/json

# {
#   "name": "Leanne Graham",
#   "username": "Bret",
#   "email": "Sincere@april.biz",
#   "address": "Kulas Light",
#   "phone": "1-770-736-8031 x56442"
# }
/////////////////////////////////////////////////////////////////////////////////////////////
#CHECK THE POSTS FUNCTIONS
GET http://localhost:3000/posts/1
Content-Type: application/json

# POST http://localhost:3000/posts
# Content-Type: application/json

# {
#   "userId": 10, 
#   "title": "Hello world", 
#   "body": "Hi, How are you?"
# }

# DELETE http://localhost:3000/posts/101